---
title: "Kaggle"
author: "Tomasz Zaremba"
date: "26.11.2015"
output: 
  html_document:
    toc: TRUE
---

# The Homework

See the Kaggle leaderboard for this problem

https://www.kaggle.com/c/walmart-recruiting-trip-type-classification/leaderboard

And the definition for the error function

https://www.kaggle.com/c/walmart-recruiting-trip-type-classification/details/evaluation

Train a model/classifier that will have score that will give you a position in top 150.

# Load the data

```{r, message=FALSE, warning=FALSE}
data <- read.table("C:\\Users\\Tomek\\Desktop\\Studia\\MSc\\Semestr 2\\Data mining\\Prace domowe\\7\\train.csv", sep=",", head=T)
library(dplyr)
```

# Solution

```{r, message=FALSE, warning=FALSE}

newdata = data %>%
  group_by(VisitNumber) %>%
  summarise(TripType = head(TripType,1),
            boughtProducts_sum = sum(ifelse(ScanCount>0, ScanCount, 0)),
            returnProducts_sum = sum(ifelse(ScanCount<0, abs(ScanCount), 0)),
            departments_count = n_distinct(DepartmentDescription),
            fineline_count = n_distinct(FinelineNumber),
            upc_sum = n(),
            day = unique(Weekday)[1])

library(tidyr)
newdata1 = data %>%
  group_by(TripType, VisitNumber, DepartmentDescription) %>%
  summarise(count = n()) %>%
  spread(DepartmentDescription, count, fill=0)

merged.data <- merge(newdata, newdata1, by=c("TripType", "VisitNumber"))

smalldata = merged.data[1:50000,]
smalldata$TripType = factor(smalldata$TripType)
names(smalldata) = make.names(names(smalldata), unique = FALSE)


library(caret)
indxTrain <- createDataPartition(y = smalldata$TripType, p = 0.75)
train <- smalldata[indxTrain$Resample1,]
test <- smalldata[-indxTrain$Resample1,]

library(randomForest)
modelFit<- randomForest(TripType~., data=train)
confusionMatrix = confusionMatrix(test$TripType, predict(modelFit,
test))$overall
round(confusionMatrix*100,2)

scores <- predict(modelFit, test, type = "prob")
myScores <- sapply(1:nrow(test), function(i){
  scores[i, test$TripType[i]]
})

mean(-log(pmax(myScores,0.05)))

```