---
title: "Homework 6"
author: "Neven Pičuljan"
date: "November 10, 2015"
output: html_document
---
# The Homework

Use the k-fold cross validation to assess the performance of lda/qda on the wines dataset.

```{r, eval=FALSE}
wines <- read.table("http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", sep=";", header=TRUE)

winesb <- wines

winesb$quality <- factor(ifelse(wines$quality > 5, "good", "bad")) 

head(winesb)
```

#Solution

```{r, eval=FALSE}
library(caret)
train_control <- trainControl(method="cv", number=10)

# LDA
# train the model 
model <- train(quality~., data=winesb, trControl=train_control, method="lda")
# make predictions
predictions <- predict(model, winesb)
# summarize results
confusionMatrix(predictions, winesb$quality)

# QDA
# train the model 
model <- train(quality~., data=winesb, trControl=train_control, method="qda")
# make predictions
predictions <- predict(model, winesb)
# summarize results
confusionMatrix(predictions, winesb$quality)
```