---
title: "Homework 1"
author: "Tomasz Kozicki"
date: "9 paüdziernika 2015"
output: html_document
---

# Home work

Use `knitr` to create a report with numerical and graphical summaries for GermanCredit.

Summarize following variables: Duration, Amount, Class, Personal.Male.Single.

## Loading data
```{r}
library(caret)
data(GermanCredit)
```

## Summarizing Duration
Number of credits for each duration
```{r}
table(GermanCredit$Duration)
summary(GermanCredit$Duration)
par(mar=c(5,5,2,2))
tab_duration <- table(GermanCredit$Duration)
barplot(tab_duration)
hist(GermanCredit$Duration, col="grey")
boxplot(GermanCredit$Duration, horizontal = TRUE)
```

## Summarizing Amount
```{r}
summary(GermanCredit$Amount)
par(mar=c(5,5,2,2))
hist(GermanCredit$Amount, col="grey")
boxplot(GermanCredit$Amount, horizontal = TRUE)
```

## Summarizing Class
```{r}
table(GermanCredit$Class)
summary(GermanCredit$Class)
par(mar=c(5,5,2,2))
tab_class <- table(GermanCredit$Class)
barplot(tab_class)
```

## Summarizing Personal.Male.Single
```{r}
table(GermanCredit$Personal.Male.Single)
summary(GermanCredit$Personal.Male.Single)
par(mar=c(5,5,2,2))
tab_single <- table(GermanCredit$Personal.Male.Single)
barplot(tab_single)
```


```{r}
table(GermanCredit$Class, GermanCredit$Personal.Male.Single)
tab <- table(GermanCredit$Class, GermanCredit$Personal.Male.Single)
tab
mosaicplot(tab)
```


