---
 title: "Homework 4"
 author: "Margareta Kusan"
 date: "October 29, 2015"
 output: html_document
---
# The Homework

 Download the dataset `adult` (find more about this dataset here: http://archive.ics.uci.edu/ml/machine-learning-databases/adult/). 

 Train a k-nn for different k and Random Forest for different `m` and compare these results with the use of ROC curves and AUC values. 

```{r, eval=FALSE}
data = read.table("http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data",
                           sep=",",header=F,col.names=c("age", "type_employer", "fnlwgt", "education", 
                                                                         "education_num","marital", "occupation", "relationship", "race","sex",
                                                                        "capital_gain", "capital_loss", "hr_per_week","country", "income"),
                           fill=FALSE,strip.white=T)
head(data,3)
```

#Solution

```{r, eval=FALSE}

library(randomForest)
library(caret)

# random forest m = 1 and knn for k = 10 
ffit <- randomForest(income ~ country+sex+education+occupation+race,   data=data, importance = TRUE, mtry = 1)
print(ffit) 
prob <- predict(ffit, type="prob")[,2]

ffit2 <- knn3(income ~ country+sex+education+occupation+race, data=data, k=10, use.all = FALSE)
prob2 <- predict(ffit2, newdata = data, type="prob")[,2]

#ROC
library(ROCR)
fit.pred = prediction(prob, data$income)
fit.perf = performance(fit.pred,"tpr","fpr")
plot(fit.perf)
fit.pred2 = prediction(prob2, data$income)
fit.perf2 = performance(fit.pred2,"tpr","fpr")
plot(fit.perf2, col="blue3", add=TRUE)

# AUC Random Forest with m = 1
fit.pred = prediction(prob, data$income)
fit.perf = performance(fit.pred,"auc")
fit.perf@y.values[[1]]

# AUC k-nn with k = 10
fit.pred = prediction(prob2, data$income)
fit.perf = performance(fit.pred,"auc")
fit.perf@y.values[[1]]

# random forest m = 3 and knn for k = 4 
ffit <- randomForest(income ~ country+sex+education+occupation+race,   data=data, importance = TRUE, mtry = 3)
print(ffit) 
prob <- predict(ffit, type="prob")[,2]

ffit2 <- knn3(income ~ country+sex+education+occupation+race, data=data, k=4, use.all = FALSE)
prob2 <- predict(ffit2, newdata = data, type="prob")[,2]

#ROC
fit.pred = prediction(prob, data$income)
fit.perf = performance(fit.pred,"tpr","fpr")
plot(fit.perf)
fit.pred2 = prediction(prob2, data$income)
fit.perf2 = performance(fit.pred2,"tpr","fpr")
plot(fit.perf2, col="blue3", add=TRUE)

# AUC Random Forest with m = 3
fit.pred = prediction(prob, data$income)
fit.perf = performance(fit.pred,"auc")
fit.perf@y.values[[1]]

# AUC k-nn with k = 20
fit.pred = prediction(prob2, data$income)
fit.perf = performance(fit.pred,"auc")
fit.perf@y.values[[1]]


```
